### ISSUE TITLE
About how to generate the dataset

### ISSUE THREAD

**Issue by FUIGUIMURONG** [adahfbch/DGM-EIT#1]
Thanks for your great work. 
I noticed that your dataset has irregular conductivity distributions. Could you please share the code used to generate this dataset?

**Comment by adahfbch** [comment]
Hi
Thanks for your interest. Can you provide me with an email so I can send you the code?

**Comment by adahfbch** [comment]
> Thanks for your great work. I noticed that your dataset has irregular conductivity distributions. Could you please share the code used to generate this dataset?

Hi
Thanks for your interest. Can you provide me with an email so I can send you the code?

**Comment by FUIGUIMURONG** [comment]
> > Thanks for your great work. I noticed that your dataset has irregular conductivity distributions. Could you please share the code used to generate this dataset?
> 
> Hi Thanks for your interest. Can you provide me with an email so I can send you the code?

Thanks for reply, and my email is 'xiaoerchen186@gmail.com'.
